language: ruby
script: "bundle exec rspec"
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
gemfile:
  - Gemfile
  - gemfiles/mongoid-2.gemfile
  - gemfiles/mongoid-3.gemfile
services:
  - mongodb
notifications:
  email:
    recipients:
      - aymerick@jehanne.org
